helm/helm:
  size: 60182712
  object_id: 7d3ad301-d7cc-4605-50a8-d347047ba4a4
  sha: sha256:ea22096683b9b61005584501e36168a1eadc5b6883a89df299f5a55e4e2dd283
jq/jq-linux64:
  size: 3953824
  object_id: d348fd24-9fb2-452c-7a42-c19eee2dcd79
  sha: sha256:af986793a515d500ab2d35f8d2aecd656e764504b789b66d7e1a0b727a124c44
kubectl/kubectl:
  size: 60133560
  object_id: 9c092535-b7d3-4c9c-4cc9-01ac9a716c78
  sha: sha256:471d94e208a89be62eb776700fc8206cbef11116a8de2dc06fc0086b0015375b
kustomize/kustomize.tar.gz:
  size: 5887075
  object_id: 1a2a3e17-9122-4035-7186-bbe7eee88d4e
  sha: sha256:c627b1575c3fecbc7ad1c181c23a7adcacf19732dab627eb57e89a7bc4c1e929
set_version.sh:
  size: 282
  object_id: cdd852a2-893e-4cd2-47cf-493ce26d4c01
  sha: sha256:3b0819f2a9880defb0c8b0b0c9e9aa64de380a90e649001ad0a7c6dd358cc003
